/* ====================================================================
 * xproto.h - S11 cross-TU prototype closure (auto-generated by
 * tools/_s11_build_xproto.py from build warning census C4013).
 *
 * Every entry below was called somewhere WITHOUT any visible prototype,
 * so MSVC assumed 'extern returning int'. For pointer-returning helpers
 * that truncated 64-bit heap pointers at the call site (cdqe effect), e.g.
 *   PECMD_HeapRealloc -> AppendWideStr -> MemMoveSafe(AV write 0x????????D4C89xxx)
 * Signatures mirror each function's actual definition in this tree;
 * provenance comment = definition location.
 * Mounted at end of stubs_common.h AND pecmd_defs.h.
 * Names listed in XPROTO_TU_LOCAL_* are intentionally NOT declared here
 * (file-local static twins exist; extern decl would break linkage).
 * ==================================================================== */
#ifndef XPROTO_H
#define XPROTO_H

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

/* S11: 8字节结构按值<=>64位整数 ABI 桥 (x64 单寄存器传/返回).
 * dc 原文以 _FILETIME/LARGE_INTEGER 传值, 移植调用点常以整数拼写; 
 * 两形态二进制兼容, 用这对内联显式转换保持语义可见. */
static __inline FILETIME S11_U64ToFT(uint64_t v)
{ FILETIME f; f.dwLowDateTime = (DWORD)(v & 0xffffffffULL);
  f.dwHighDateTime = (DWORD)(v >> 32); return f; }
static __inline uint64_t S11_FTToU64(FILETIME f)
{ return ((uint64_t)f.dwHighDateTime << 32) | f.dwLowDateTime; }
static __inline LARGE_INTEGER S11_U64ToLI(uint64_t v)
{ LARGE_INTEGER l; l.QuadPart = (int64_t)v; return l; }
static __inline uint64_t S11_LIToU64(LARGE_INTEGER l)
{ return (uint64_t)l.QuadPart; }
static __inline ULARGE_INTEGER S11_U64ToULI(uint64_t v)
{ ULARGE_INTEGER u; u.QuadPart = (int64_t)v; return u; }

/* 1 site(s) */ extern void AtlThrowImpl(long); /* def src\commands\core_b3b.c:74 */
/* 1 site(s) */ extern int FUN_140003864(void *a, const uint16_t *b, uint32_t, uint32_t, void *e, uint32_t, uint32_t, void *h); /* def unimplemented_stubs.c:406 */
/* 1 site(s) */ extern uint64_t FUN_1400048c4(int64_t *a); /* def unimplemented_stubs.c:409 */
/* 1 site(s) */ extern uint64_t FUN_14000C764(LPCWSTR p); /* dc 原文权威签名(S11) */
/* 1 site(s) */ extern uint32_t FUN_14000bfcc(uint64_t, uint64_t, const uint16_t *c); /* def unimplemented_stubs.c:411 */
/* 1 site(s) */ extern void    * FUN_140017770(void *a, const char *b); /* def restored_bodies.c:12890 */
/* 1 site(s) */ extern void FUN_1400177b8(void *a); /* def unimplemented_stubs.c:410 */
/* 1 site(s) */ extern int64_t FUN_140018978(int64_t *a, const uint16_t *b, int64_t *c, int64_t, void *e); /* def restored_bodies.c:12843 */
/* 5 site(s) */ extern int64_t FUN_14001C2CC(LPCWSTR, DWORD, uint32_t); /* def src\device\core_sys.c:289 */
/* 1 site(s) */ extern uint64_t FUN_14001b7f4(const uint16_t *a); /* def restored_bodies.c:12876 */
/* 1 site(s) */ extern uint32_t FUN_14001ebdc(LPCWSTR a, int64_t *b); /* dc 原文权威签名(S11) */
/* 1 site(s) */ extern void FUN_140025f10(int64_t, LPCWSTR, uint32_t, char *param_4, char *param_5, long long *param_6); /* def restored_bodies.c:4611 */
/* 1 site(s) */ extern void FUN_140053e78(void); /* def unimplemented_stubs.c:95 */
/* 2 site(s) */ extern WCHAR ** FUN_14005B154(WCHAR **pp); /* def src\kernel\core_string.c:173 */
/* 1 site(s) */ extern DWORD FUN_14005C394(HKEY, LPCWSTR, HKEY *out, REGSAM, uint32_t); /* def src\device\core_sys.c:262 */
/* 4 site(s) */ extern DWORD FUN_14005C4E0(HKEY, LPCWSTR, LPCWSTR, DWORD *type, BYTE *data, DWORD *size); /* def src\device\core_sys.c:234 */
/* 14 site(s) */ extern int FUN_14005C788(const char *s, const WCHAR *w, int); /* def src\kernel\core_string.c:187 */
/* 1 site(s) */ extern void    * FUN_14005b374(void *a, int16_t, int16_t); /* def unimplemented_stubs.c:407 */
/* 1 site(s) */ extern void FUN_14005b540(uint16_t *a, int); /* def unimplemented_stubs.c:413 */
/* 1 site(s) */ extern int64_t FUN_14005bbb4(int64_t *a); /* def unimplemented_stubs.c:384 */
/* 1 site(s) */ extern int FUN_14005bc28(uint16_t); /* def unimplemented_stubs.c:383 */
/* 1 site(s) */ extern void FUN_14005bc48(int64_t, double *param_2, double); /* def unimplemented_stubs.c:397 */
/* 1 site(s) */ extern void FUN_14005bc5c(int64_t, double *param_2, double); /* def unimplemented_stubs.c:399 */
/* 1 site(s) */ extern uint64_t FUN_14005c788(char *a, uint16_t *b, int); /* def unimplemented_stubs.c:492 */
/* 1 site(s) */ extern uint64_t FUN_14005e0a0(void); /* def unimplemented_stubs.c:402 */
/* 1 site(s) */ extern uint64_t FUN_14005ea5c(void); /* def unimplemented_stubs.c:405 */
/* 3 site(s) */ extern int FUN_1400630D0(int); /* def src\kernel\core_string.c:209 */
/* 2 site(s) */ extern uint64_t FUN_140063344(void *p); /* def unimplemented_stubs.c:297 */
/* 1 site(s) */ extern uint64_t FUN_140063424(void *param_1, int64_t); /* def restored_bodies.c:12874 */
/* 21 site(s) */ extern WCHAR * FUN_14006375C(WCHAR **ps, LPCWSTR); /* def src\kernel\core_string.c:108 */
/* 2 site(s) */ extern int64_t FUN_140064A88(const WCHAR *p); /* def src\device\core_sys.c:167 */
/* 1 site(s) */ extern int64_t FUN_140065864(int64_t, int64_t *param_2, int64_t *param_3, uint8_t *param_4, uint32_t); /* def restored_bodies.c:12853 */
/* 1 site(s) */ extern void FUN_1400675b8(int64_t *param_1, int64_t *param_2, int16_t); /* def restored_bodies.c:12869 */
/* 1 site(s) */ extern void FUN_1400676e4(int64_t *param_1, int64_t *param_2, int16_t); /* def restored_bodies.c:12870 */
/* 1 site(s) */ extern void FUN_140067748(int64_t *param_1, int64_t *param_2, int16_t); /* def restored_bodies.c:12871 */
/* 1 site(s) */ extern uint64_t FUN_140067d54(int64_t *pcursor, double *out); /* def src\ui\core_b7c.c:4451 */
/* 1 site(s) */ extern void    * FUN_14006e3a4(const WCHAR *a); /* def restored_bodies.c:12894 */
/* 22 site(s) */ extern void FUN_1400702B0(WCHAR **ps, LPCWSTR); /* def src\kernel\core_string.c:154 */
/* 1 site(s) */ extern uint32_t FUN_1400734e4(int64_t, void *param_2, int64_t *param_3); /* def restored_bodies.c:12872 */
/* 1 site(s) */ extern uint32_t FUN_140073CCC(void *script, LPCWSTR, int); /* def src\runtime\core_exec5.c:204 */
/* 1 site(s) */ extern long FUN_140096f84(void *param_1, void *param_2, void *param_3); /* def restored_bodies.c:12873 */
/* 1 site(s) */ extern int64_t FUN_1400f5608(int64_t, int, int *pwidth); /* def src\ui\core_b7c.c:4962 */
/* 1 site(s) */ extern int64_t FUN_1400f59c0(int64_t, int, int *pwidth); /* def src\ui\core_b7c.c:4978 */
/* 1 site(s) */ extern int64_t FUN_1401001c0(int64_t, int64_t *param_2, uint64_t, uint64_t); /* def src\misc\core_b9_remaining.c:118 */
/* 1 site(s) */ extern bool FUN_140101E70(LPCWSTR); /* def src\lang\core_exec2.c:166 */
/* 1 site(s) */ extern void FUN_140101db8(void *param_1, const void *param_2, void *param_3); /* def restored_bodies.c:12875 */
/* 1 site(s) */ extern bool FUN_140101e70(LPCWSTR); /* def restored_bodies.c:9615 */
/* 1 site(s) */ extern void FUN_140102a90(uint64_t *dst, uint64_t, uint64_t); /* def unimplemented_stubs.c:267 */
/* 1 site(s) */ extern double FUN_140104b00(double); /* def crt_shims.c:18 */
/* 1 site(s) */ extern double FUN_140104e08(double); /* def crt_shims.c:30 */
/* 1 site(s) */ extern double FUN_14010511c(double); /* def crt_shims.c:41 */
/* 1 site(s) */ extern double FUN_1401053a8(double); /* def crt_shims.c:51 */
/* 1 site(s) */ extern double FUN_1401055ec(double); /* def crt_shims.c:62 */
/* 1 site(s) */ extern double FUN_1401058cc(double); /* def crt_shims.c:72 */
/* 1 site(s) */ extern double FUN_140105bc0(uint64_t); /* def crt_shims.c:82 */
/* 1 site(s) */ extern double FUN_140105f10(double, double); /* def crt_shims.c:92 */
/* 1 site(s) */ extern double FUN_140106654(double); /* def crt_shims.c:103 */
/* 1 site(s) */ extern double FUN_14010697c(double); /* def crt_shims.c:113 */
/* 1 site(s) */ extern double FUN_140106c5c(double); /* def crt_shims.c:123 */
/* 1 site(s) */ extern double FUN_140107468(double, double); /* def crt_shims.c:133 */
/* 1 site(s) */ extern uint64_t PECMD_AddControlStar(LPCWSTR, uint16_t *param_2, uintptr_t); /* def src\commands\core_b3r_i28d.c:77 */
/* 1 site(s) */ extern uint64_t PECMD_AddControlVariantB(int64_t *param_1, WCHAR *param_2, int64_t, uint64_t); /* def src\commands\core_b3r_i28d.c:341 */
/* 1 site(s) */ extern uint64_t PECMD_AddControlWide(int64_t *param_1, WCHAR *param_2, uintptr_t, uint64_t); /* def src\commands\core_b3r_i28d.c:160 */
/* 1 site(s) */ extern int64_t PECMD_AddImagesToImageList(int64_t, LPCWSTR); /* def src\misc\core_b9_remaining.c:75 */
/* 1 site(s) */ extern uint64_t PECMD_AddTransControl(int64_t *param_1, uint16_t *param_2, uintptr_t, uint64_t); /* def src\commands\core_b3r_i28d.c:491 */
/* 1 site(s) */ extern void PECMD_AdoptRefCountedString(WCHAR **ps, LPCWSTR); /* def src\lang\core_exec4.c:249 */
/* 1 site(s) */ extern uint8_t PECMD_AdvanceAfterPrefix(LPCWSTR, int64_t *param_2, int); /* def src\misc\core_b1_remaining.c:9028 */
/* 1 site(s) */ extern void PECMD_AllocExpandPath(void *a, int64_t *b); /* def unimplemented_stubs.c:281 */
/* 1 site(s) */ extern void PECMD_AllocFileReqEmbedPath(int64_t *out, uint64_t *src); /* def src\commands\core_b3f.c:477 */
/* 4 site(s) */ extern uint16_t * PECMD_AllocStrSlot(uint16_t **out); /* def restored_bodies.c:7339 */
/* 27 site(s) */ extern WCHAR * PECMD_AllocString(WCHAR **ps, int64_t); /* def src\kernel\core_string.c:96 */
/* 1 site(s) */ extern void PECMD_AppendFormattedI64(int64_t *a, int64_t); /* def unimplemented_stubs.c:275 */
/* 1 site(s) */ extern void PECMD_AppendKeyIfMissing(int64_t, LPCWSTR, int); /* def src\misc\core_b1_remaining.c:7191 */
/* 1 site(s) */ extern void PECMD_AppendQuotedString(int64_t *a, void *b, int); /* def unimplemented_stubs.c:408 */
/* 1 site(s) */ extern void PECMD_AppendString(int64_t *param_1, int64_t *param_2, int64_t *param_3, LPCWSTR); /* def src\misc\core_b1_remaining.c:9162 */
/* 2 site(s) */ extern int64_t * PECMD_AppendWideStr(void *param_1p, LPCWSTR); /* def restored_bodies.c:7358 */
/* 1 site(s) */ extern uint64_t PECMD_ApplyWallpaper(WCHAR *path); /* def src\commands\core_b2a.c:330 */
/* 1 site(s) */ extern void PECMD_ArrayGrowRaw(uint64_t *arr, int64_t *cap, uint32_t, int64_t); /* def src\commands\core_b3h.c:456 */
/* 2 site(s) */ extern int PECMD_AsciiPrefixICmp(const char *a, const uint16_t *w, int); /* def unimplemented_stubs.c:100 */
/* 1 site(s) */ extern uint16_t * PECMD_AssignIfEmpty(WCHAR **pp, LPCWSTR); /* def src\misc\core_b1_remaining.c:7049 */
/* 1 site(s) */ extern uint64_t PECMD_AttachControlImage(int64_t *param_1, LPCWSTR); /* def src\commands\core_b3r_i28f.c:662 */
/* 1 site(s) */ extern uint64_t PECMD_Base64Decode(uint8_t *param_1, uint64_t *param_2); /* def src\commands\core_b3_remaining.c:14980 */
/* 1 site(s) */ extern void PECMD_BroadcastEnvChange(void); /* def src\app\core_init.c:146 */
/* 1 site(s) */ extern void PECMD_CacheSysColors(void); /* def src\commands\core_b3c.c:168 */
/* 1 site(s) */ extern LPWSTR PECMD_CalcExpression(int64_t *param_1, WCHAR *param_2, uint64_t *param_3); /* def src\commands\core_b3_remaining.c:28359 */
/* 1 site(s) */ extern void * PECMD_CheckInfDriver(int64_t *a, uint64_t, char *c); /* def unimplemented_stubs.c:282 */
/* 1 site(s) */ extern int64_t PECMD_CodeConvertCommand(void *script, WCHAR *args); /* def src\commands\core_cmd4.c:93 */
/* 1 site(s) */ extern int64_t PECMD_CompareStringWrap(LPCWSTR, LPCWSTR, int, int); /* def src\commands\core_b3a.c:82 */
/* 1 site(s) */ extern int PECMD_ConvertValue(int); /* def src\commands\core_b3d.c:159 */
/* 1 site(s) */ extern uint64_t PECMD_CopyPathToken(int64_t, int64_t *b, int64_t *c, int64_t); /* def unimplemented_stubs.c:194 */
/* 1 site(s) */ extern void PECMD_CopyTokenTrimmed(int64_t *pp, int64_t *out, int16_t, int16_t); /* def src\commands\core_b3j.c:519 */
/* 1 site(s) */ extern int PECMD_CountNewlines(uint64_t *param_1, int, int, int); /* def restored_bodies.c:10472 */
/* 1 site(s) */ extern int PECMD_CountStripEscape(LPCWSTR); /* def src\misc\core_b1_remaining.c:9071 */
/* 1 site(s) */ extern uint64_t PECMD_CreateButtonControl(int64_t *param_1, WCHAR *param_2, uintptr_t, uint64_t); /* def src\commands\core_b3r_i28e.c:780 */
/* 1 site(s) */ extern void PECMD_CreateCleanupThread(void *task); /* def src\commands\core_b2a.c:232 */
/* 1 site(s) */ extern bool PECMD_CreateCustomChildControl(int64_t *param_1, uint32_t, int *param_3, HWND, uint32_t, LPCWSTR); /* def restored_bodies.c:9825 */
/* 1 site(s) */ extern bool PECMD_CreateDateTimePickCtl(int64_t *a, uint32_t b, int *c, HWND h, uint32_t e); /* dc 原文权威签名(S11) */
/* 1 site(s) */ extern DWORD PECMD_CreateDirectory(uint64_t, WCHAR *path); /* def src\commands\core_b2a.c:385 */
/* 1 site(s) */ extern uint64_t PECMD_CreateDirectoryTree(LPCWSTR); /* def src\misc\core_b1_remaining.c:9209 */
/* 1 site(s) */ extern bool PECMD_CreateIpAddressCtl(int64_t *param_1, DWORD, int *param_3, void *param_4, uint32_t); /* def restored_bodies.c:9816 */
/* 1 site(s) */ extern uint8_t * PECMD_CreateMenuItem(int64_t *param_1, int16_t *param_2); /* def src\commands\core_b3r_h4.c:724 */
/* 1 site(s) */ extern bool PECMD_CreateProgressCtl(int64_t *a, uint32_t b, int *c, HWND h, uint32_t e); /* dc 原文权威签名(S11) */
/* 1 site(s) */ extern uint64_t PECMD_CreateSymbolicLink(uint64_t, uint64_t, uint32_t); /* def src\commands\core_b3g.c:308 */
/* 1 site(s) */ extern HANDLE PECMD_CreateTempMutexDir(int64_t *param_1, int64_t *param_2, uint64_t *param_3, uint64_t, uint64_t); /* def src\misc\core_b1_remaining.c:3561 */
/* 1 site(s) */ extern uint64_t PECMD_CreateTextControl(int64_t *param_1, WCHAR *param_2, uintptr_t, uint64_t); /* def src\device\core_b3r_g.c:581 */
/* 1 site(s) */ extern int64_t PECMD_DefineDosDevice(int64_t *param_1, WCHAR *param_2); /* def src\commands\core_b3_remaining.c:17811 */
/* 1 site(s) */ extern LPCWSTR PECMD_DerefVarName(void *script, WCHAR **pp); /* def src\commands\core_b2a.c:269 */
/* 1 site(s) */ extern uint32_t PECMD_DetectMinintBoot(void); /* def src\misc\core_b1_remaining.c:5540 */
/* 1 site(s) */ extern uint32_t PECMD_DevconUpdate(int64_t, LPCWSTR, LPCWSTR, int); /* def src\commands\core_b2b.c:1011 */
/* 1 site(s) */ extern FILETIME PECMD_DirWildcardExpand(int64_t *script, FILETIME arg); /* dc 原文权威签名(S11) */
/* 1 site(s) */ extern int PECMD_DispatchBuiltin(int64_t *param_1, uintptr_t, LPCWSTR, LPCWSTR, FILETIME *param_5); /* def src\misc\core_b1_remaining.c:5602 */
/* 1 site(s) */ extern uint64_t PECMD_DispatchCommand(int64_t *script, LPCWSTR, int64_t *out); /* def src\commands\core_b3e.c:92 */
/* 1 site(s) */ extern uint32_t PECMD_DispatchSpecialDirective(int64_t *pp, uint16_t *s); /* def src\commands\core_b3i.c:101 */
/* 1 site(s) */ extern uint64_t PECMD_DriveLetterSet(uint64_t, LPCWSTR); /* def src\device\core_b3r_g7.c:123 */
/* 1 site(s) */ extern uint64_t PECMD_DrvLoadInstall(int64_t, void *b, void *c, int); /* def restored_bodies.c:10615 */
/* 1 site(s) */ extern int PECMD_EnumClassDevices(uint32_t, LPCWSTR, uint32_t, int64_t *param_4, uint16_t *param_5); /* def src\commands\core_b3_remaining.c:16969 */
/* 1 site(s) */ extern uint64_t PECMD_EnumProcessInfo(uint16_t *s, int, int64_t *p, int, unsigned long); /* def restored_bodies.c:11132 */
/* 1 site(s) */ extern uint64_t PECMD_EvalParenExprRounded(int64_t *a, uint64_t *b); /* dc 原文权威签名(S11) */
/* 1 site(s) */ extern uint64_t PECMD_ExecCmdDispatch(uint64_t, uint64_t, uint64_t, uint64_t, uint64_t, uint64_t, uint64_t, uint64_t); /* def restored_bodies.c:256 */
/* 1 site(s) */ extern LARGE_INTEGER PECMD_ExecCommandLine(int64_t *script, LPCWSTR arg); /* dc 原文权威签名(S11) */
/* 1 site(s) */ extern int64_t PECMD_ExecPathList(int64_t *script, LPCWSTR, uint64_t, int64_t *out, void *ctx); /* def src\commands\core_b2c.c:999 */
/* 1 site(s) */ extern int64_t PECMD_ExecSubCommand(int64_t *script, WCHAR *cmd, int64_t *out, LPCWSTR, uint32_t); /* def src\commands\core_b2c.c:847 */
/* 1 site(s) */ extern LPCWSTR PECMD_ExpandBackslashNewline(LPCWSTR, char); /* def src\misc\core_b1_remaining.c:8986 */
/* 1 site(s) */ extern uint64_t PECMD_ExpandPathAlloc2(LPCWSTR, uint64_t *param_2, int64_t *param_3); /* def restored_bodies.c:9514 */
/* 1 site(s) */ extern LPCWSTR PECMD_ExtractTableSegment(int64_t, uint64_t *param_2, uint16_t *param_3, int64_t *param_4, char); /* def src\misc\core_b1_remaining.c:7933 */
/* 1 site(s) */ extern uint64_t PECMD_FindCmdHandler(int64_t *obj, ULARGE_INTEGER, int64_t *out, uint64_t); /* def src\commands\core_b2a.c:151 */
/* 1 site(s) */ extern void PECMD_FindFirstFileW(HANDLE *ph, LPCWSTR, WIN32_FIND_DATAW *fd); /* def src\misc\core_b9_remaining.c:177 */
/* 1 site(s) */ extern LPCWSTR PECMD_FindQuotedToken(LPCWSTR, LPCWSTR, int, uint32_t); /* def src\commands\core_b2b.c:686 */
/* 1 site(s) */ extern uint64_t PECMD_FindTargetWindow(LPCWSTR, char, char, HWND, uint32_t, uint32_t, uint64_t, uint64_t); /* def src\ui\core_b8g.c:110 */
/* 1 site(s) */ extern void PECMD_FlushLogBuffer(char, int64_t *param_2); /* def src\misc\core_b1_remaining.c:6400 */
/* 1 site(s) */ extern ULONGLONG PECMD_ForCommand(int64_t *param_1, WCHAR *param_2, int64_t *param_3, int64_t *param_4, uint64_t); /* def src\commands\core_b3r_i28b.c:424 */
/* 1 site(s) */ extern void PECMD_FormatOutput(int64_t); /* def src\commands\core_b3d.c:507 */
/* 1 site(s) */ extern void PECMD_FormatSetVar(int64_t *script, uint64_t, LPCWSTR, LPCWSTR); /* def src\commands\core_b3e.c:472 */
/* 1 site(s) */ extern int64_t PECMD_FormatTimeString(int64_t *param_1, WCHAR *param_2); /* def src\commands\core_b3r_h4.c:957 */
/* 1 site(s) */ extern int64_t PECMD_FormatVolume(int64_t *param_1, WCHAR *param_2); /* def src\device\core_b3r_g6.c:55 */
/* 1 site(s) */ extern void PECMD_FreeAndFree(uint64_t *slot); /* def src\commands\core_b3c.c:78 */
/* 1 site(s) */ extern void PECMD_FreePointerSlot(uint64_t *slot); /* def src\commands\core_b3a.c:109 */
/* 1 site(s) */ extern uint64_t PECMD_GenerateTextContent(int64_t *param_1, int64_t); /* def src\device\core_b3r_h1.c:669 */
/* 1 site(s) */ extern LPCWSTR PECMD_GetDiskFreeSpace(int64_t *param_1, WCHAR *param_2); /* def src\device\core_b3r_h1.c:1819 */
/* 1 site(s) */ extern void PECMD_GetEnvVarToStr(LPCWSTR, uint64_t *param_2); /* def restored_bodies.c:7549 */
/* 1 site(s) */ extern uint64_t PECMD_GetPathSizeToVar(int64_t *script, LARGE_INTEGER arg); /* dc 原文权威签名(S11) */
/* 1 site(s) */ extern int32_t PECMD_GetPathType(WCHAR *s); /* def src\commands\core_b2a.c:248 */
/* 1 site(s) */ extern uint16_t * PECMD_GetStringToken(int64_t *param_1, uint16_t); /* def src\misc\core_b1_remaining.c:9099 */
/* 1 site(s) */ extern void PECMD_GetTaskbarCreatedMsg(void); /* def src\device\core_sys.c:150 */
/* 1 site(s) */ extern int64_t PECMD_GetWinIdLocked(int64_t *param_1); /* def restored_bodies.c:9735 */
/* 1 site(s) */ extern void PECMD_HardlinkOrCopy(LPCWSTR, LPCWSTR, int); /* def restored_bodies.c:12878 */
/* 1 site(s) */ extern void * PECMD_HeapRealloc(void *ptr, size_t); /* def src\kernel\core_string.c:38 */
/* 1 site(s) */ extern uint64_t PECMD_HotkeyControl(int64_t *script, WCHAR *cmdline, int); /* def src\commands\core_b2e.c:178 */
/* 1 site(s) */ extern uint64_t PECMD_IfexCmdHandler(int64_t *obj, ULARGE_INTEGER, int64_t *out, uint64_t); /* def src\commands\core_b2a.c:140 */
/* 1 site(s) */ extern int64_t PECMD_ImageCommand(LPCWSTR, LPCWSTR, uintptr_t); /* def src\commands\core_b3r_i28f.c:317 */
/* 1 site(s) */ extern void PECMD_InitControlObjC(void *a, void *b); /* dc 原文权威签名(S11) */
/* 1 site(s) */ extern void PECMD_InitDragDrop(int64_t a, uint32_t b, int64_t c); /* dc 原文权威签名(S11) */
/* 1 site(s) */ extern void PECMD_InitEditBuffer(int64_t, uint16_t *p); /* def src\misc\core_b1_remaining.c:7135 */
/* 1 site(s) */ extern int64_t * PECMD_InitPtrTable(int64_t *arr); /* def src\commands\core_b3i.c:539 */
/* 1 site(s) */ extern uint32_t * PECMD_InitScriptContext(uint32_t *param_1); /* def src\misc\core_b1_remaining.c:9402 */
/* 1 site(s) */ extern void * PECMD_InstallInfDevice(void *p); /* def unimplemented_stubs.c:276 */
/* 1 site(s) */ extern uint32_t PECMD_InstallPlugPlayDriver(long long, LPCWSTR, LPCWSTR, uint32_t, int, uint8_t *param_6); /* def restored_bodies.c:10531 */
/* 2 site(s) */ extern uint64_t PECMD_IsDirectory(LPCWSTR); /* def src\misc\core_b9_remaining.c:152 */
/* 1 site(s) */ extern uint64_t PECMD_IsRemovableDrive(uint16_t); /* def src\misc\core_b9_remaining.c:136 */
/* 1 site(s) */ extern int PECMD_IsSetupClass(const void *pguid, const char *name); /* dc 原文权威签名(S11) */
/* 1 site(s) */ extern LPCWSTR PECMD_LangLookupById(int, LPCWSTR *param_2); /* def restored_bodies.c:4218 */
/* 1 site(s) */ extern int64_t PECMD_LaunchAsyncScriptThread(int64_t *param_1, WCHAR *param_2, uint64_t); /* def src\commands\core_b3r_i28c.c:846 */
/* 1 site(s) */ extern uint64_t PECMD_LaunchCommand(uint16_t *param_1); /* def src\commands\core_b3_remaining.c:1363 */
/* 1 site(s) */ extern uint64_t PECMD_LaunchShell(LPCWSTR); /* def src\commands\core_b3_remaining.c:1235 */
/* 1 site(s) */ extern int64_t PECMD_LinkFile(int64_t *param_1, LPCWSTR); /* def src\device\core_b3r_h2.c:320 */
/* 1 site(s) */ extern HICON PECMD_LoadIconAndTooltip(int64_t *param_1, LPCWSTR, int64_t); /* def src\commands\core_b3r_i28e.c:252 */
/* 2 site(s) */ extern LPCWSTR PECMD_LoadLocalizedString(void *hinst, unsigned int id, WCHAR *buf, int len); /* dc 原文权威签名(S11) */
/* 1 site(s) */ extern uint64_t PECMD_LoadTasksWait(int64_t *param_1, LPCWSTR, int64_t); /* def src\commands\core_b3r_h4.c:1352 */
/* 1 site(s) */ extern int64_t PECMD_LoadUnloadRegistryHive(int64_t *param_1, uint16_t *param_2); /* def src\commands\core_b3_remaining.c:22889 */
/* 1 site(s) */ extern bool PECMD_MatchAndAdvance(char *key, int64_t *pp, int); /* def src\commands\core_b3d.c:408 */
/* 1 site(s) */ extern uint64_t PECMD_MatchAssignToken(char *key, int64_t *pp, int); /* def src\commands\core_b3f.c:317 */
/* 1 site(s) */ extern uint64_t PECMD_MatchPattern(int16_t *pattern, int64_t); /* def src\commands\core_b3c.c:212 */
/* 1 site(s) */ extern int64_t PECMD_MatchPatternWithQuotes(LPCWSTR, LPCWSTR); /* def src\commands\core_b2a.c:421 */
/* 1 site(s) */ extern uint8_t PECMD_MatchTokPrefixAdv(LPCWSTR, int64_t *param_2, int); /* def restored_bodies.c:12096 */
/* 1 site(s) */ extern uint64_t PECMD_MsgCommand(int64_t *param_1, WCHAR *param_2, uintptr_t, uint64_t); /* def src\device\core_b3r_h1.c:151 */
/* 1 site(s) */ extern uint64_t PECMD_MsgDispatch(int64_t *param_1, uint16_t *param_2, uintptr_t, uint64_t); /* def src\device\core_b3r_h1.c:544 */
/* 1 site(s) */ extern uint64_t PECMD_NormalizePath(int64_t *param_1, LPCWSTR); /* def src\device\core_b3r_h1.c:2062 */
/* 1 site(s) */ extern char PECMD_NormalizeVolumeDevPath(LPCWSTR *ps); /* def src\lang\core_exec4.c:151 */
/* 1 site(s) */ extern uint64_t PECMD_NotifyMainWindowRefresh(uint64_t, int); /* def unimplemented_stubs.c:138 */
/* 1 site(s) */ extern uint64_t PECMD_OomPrompt(int); /* def unimplemented_stubs.c:298 */
/* 1 site(s) */ extern HANDLE PECMD_OpenLockVolume(int, uint64_t, int64_t, uint32_t, WCHAR *param_5); /* def src\misc\core_b1_remaining.c:3128 */
/* 1 site(s) */ extern int PECMD_ParseCharClassRanges(int *arr, int64_t *pp, uint32_t); /* def src\commands\core_b3l.c:144 */
/* 1 site(s) */ extern uint64_t PECMD_ParseComboList(int64_t *param_1, uint16_t *param_2, uintptr_t, uint64_t); /* def src\commands\core_b3r_i28a.c:231 */
/* 1 site(s) */ extern uint64_t PECMD_ParseCommandBlock(int64_t, WCHAR **pp, uint32_t, void *threadInfo); /* def src\commands\core_b2d.c:451 */
/* 1 site(s) */ extern uint64_t PECMD_ParseCommandPath(uint64_t, uint64_t, uint32_t *c, int64_t *d); /* def unimplemented_stubs.c:186 */
/* 1 site(s) */ extern uint64_t PECMD_ParseControlCenterArgs(int64_t *param_1, uint16_t *param_2, uintptr_t, uint64_t); /* def src\commands\core_b3r_i28b.c:271 */
/* 1 site(s) */ extern uint64_t PECMD_ParseControlCommand(int64_t *param_1, LPWSTR, uintptr_t); /* def src\commands\core_b3r_i28a.c:562 */
/* 1 site(s) */ extern uint64_t PECMD_ParseControlDef(int64_t *param_1, LPCWSTR, uintptr_t); /* def src\commands\core_b3r_i28f.c:76 */
/* 1 site(s) */ extern FILETIME PECMD_ParseDateTimeSpec(int64_t *script, FILETIME cmd, uint32_t flags, FILETIME fmt); /* dc 原文权威签名(S11) */
/* 1 site(s) */ extern void PECMD_ParseDeviceClassGuid(LPCWSTR, void *param_2, uint64_t *param_3, uint8_t *param_4); /* def src\misc\core_b1_remaining.c:7262 */
/* 1 site(s) */ extern int64_t PECMD_ParseExtPathArg(int64_t *param_1, short *param_2); /* def src\device\core_b3r_h2.c:182 */
/* 1 site(s) */ extern short PECMD_ParseHashNumbers(int64_t *pp, int64_t val); /* dc 原文权威签名(S11) */
/* 1 site(s) */ extern bool PECMD_ParseHexOrDecBool(long long *param_1, int *param_2); /* def restored_bodies.c:7930 */
/* 1 site(s) */ extern uint64_t PECMD_ParseHlpDoc(uint64_t, LPCWSTR); /* def src\commands\core_b3_remaining.c:901 */
/* 1 site(s) */ extern void PECMD_ParseIntSkipSepChar(uint64_t *pp, int *out, int16_t sep); /* dc 原文权威签名(S11) */
/* 1 site(s) */ extern uint64_t PECMD_ParseListControl(int64_t *param_1, uint16_t *param_2, uintptr_t, uint64_t); /* def src\commands\core_b3r_i28a.c:394 */
/* 1 site(s) */ extern uint32_t PECMD_ParseLtwhFlags(int64_t *param_1, uint32_t *param_2); /* def src\commands\core_b3r_d.c:243 */
/* 1 site(s) */ extern uint64_t PECMD_ParseMsgDispatch(int64_t *param_1, uint16_t *param_2, uintptr_t, uint64_t); /* def src\device\core_b3r_h1.c:417 */
/* 1 site(s) */ extern void PECMD_ParseNumSkipChar_01f8(int64_t *pp, int *out); /* def src\commands\core_b3b.c:360 */
/* 1 site(s) */ extern bool PECMD_ParseNumSkipWs(WCHAR **pp, uint64_t *out); /* def src\misc\core_remaining_helpers.c:118 */
/* 1 site(s) */ extern int PECMD_ParseNumberToken(int64_t *pp, int *out); /* dc 原文权威签名(S11) */
/* 1 site(s) */ extern LPCWSTR PECMD_ParseResourceStringRef(LPCWSTR *param_1, uint32_t); /* def restored_bodies.c:7604 */
/* 1 site(s) */ extern void PECMD_ParseSkipSeparator(int64_t *pp, int64_t *out, int16_t, int16_t); /* def src\commands\core_b3e.c:111 */
/* 1 site(s) */ extern uint64_t PECMD_ParseValueCommand(void *script, void *value, uint64_t); /* def src\commands\core_b2a.c:90 */
/* 1 site(s) */ extern uint64_t PECMD_ParseWindowPosition(int64_t *param_1, WCHAR *param_2, uintptr_t); /* def src\commands\core_b3r_i28e.c:101 */
/* 1 site(s) */ extern int64_t PECMD_PcipCommand(int64_t *param_1, LPCWSTR); /* def src\commands\core_b3r_i28c.c:123 */
/* 1 site(s) */ extern uint64_t PECMD_PcipDispatch(int64_t *param_1, uint16_t *param_2, uintptr_t, uint64_t); /* def src\commands\core_b3r_i28c.c:1350 */
/* 1 site(s) */ extern uint64_t PECMD_ProcessEncodedFile(int64_t *param_1, WCHAR *param_2); /* def src\device\core_b3r_h1.c:1296 */
/* 1 site(s) */ extern int64_t PECMD_QueryRecycleBinVolume(int64_t *param_1, short *param_2); /* def src\device\core_b3r_g7.c:286 */
/* 1 site(s) */ extern uint64_t PECMD_RandSeedAdvance(void); /* dc 原文权威签名(S11) */
/* 1 site(s) */ extern LARGE_INTEGER PECMD_ReadTextLine(int64_t *script, FILETIME arg); /* dc 原文权威签名(S11) */
/* 1 site(s) */ extern int PECMD_ReenumerateDevice(uint32_t); /* def src\misc\core_b1_remaining.c:7243 */
/* 1 site(s) */ extern DWORD PECMD_RegOpenWithRetryPriv(HKEY, LPCWSTR, HKEY*, REGSAM, uint32_t); /* def restored_bodies.c:10023 */
/* 1 site(s) */ extern void PECMD_RegReadWrap(HKEY, LPCWSTR, LPCWSTR, int64_t *out, DWORD *type, LONG *status); /* def src\commands\core_b3b.c:292 */
/* 1 site(s) */ extern void PECMD_ResetScriptChain(int64_t *param_1, int64_t *param_2); /* def restored_bodies.c:13967 */
/* 1 site(s) */ extern uint64_t PECMD_RunExeIndata(LPCWSTR); /* def src\device\core_b3r_g7.c:403 */
/* 1 site(s) */ extern uint32_t PECMD_RunProcessCommand(int64_t, LPCWSTR, uint64_t, uint64_t, uint64_t); /* def src\commands\core_b2b.c:884 */
/* 1 site(s) */ extern uint64_t PECMD_RunRamdriv(int64_t *ctx, LPCWSTR); /* def src\commands\core_b2b.c:1148 */
/* 1 site(s) */ extern void PECMD_ScanDeviDirInfFiles(void *a, uint64_t, uint64_t, int, void *e); /* def unimplemented_stubs.c:283 */
/* 1 site(s) */ extern uint64_t PECMD_ScreenAreaCommand(int64_t *param_1, LPCWSTR); /* def src\device\core_b3r_h2.c:834 */
/* 1 site(s) */ extern LPCWSTR * PECMD_SearchStringAndLocate(int64_t *param_1, WCHAR *param_2, uint64_t, uint8_t); /* def src\commands\core_b3r_h3.c:430 */
/* 1 site(s) */ extern uint64_t PECMD_SendColorMsg(long long, uint32_t, uint32_t, uint32_t, uint32_t); /* def restored_bodies.c:9684 */
/* 1 site(s) */ extern uint64_t PECMD_ServiceControl(int64_t *script, LPCWSTR); /* def src\commands\core_b2f.c:170 */
/* 1 site(s) */ extern void PECMD_SetCheckVariable(int64_t param_1, int param_2); /* dc 原文权威签名(S11) */
/* 1 site(s) */ extern void PECMD_SetControlState(int64_t a, uint32_t b, LPWSTR c); /* dc 原文权威签名(S11) */
/* 1 site(s) */ extern int64_t PECMD_SetFbwfThreshold(uint64_t, LPWSTR); /* def src\commands\core_b2a.c:191 */
/* 1 site(s) */ extern int64_t PECMD_SetFileNameExtension(int64_t *script, uint16_t *spec); /* def src\commands\core_b3m.c:1326 */
/* 1 site(s) */ extern uint64_t PECMD_SetNumLockState(LPCWSTR); /* def src\misc\core_b1_remaining.c:7710 */
/* 1 site(s) */ extern void PECMD_SetVarCore(int64_t *script, LPCWSTR key, LPCWSTR val, int64_t n); /* dc 原文权威签名(S11) */
/* 1 site(s) */ extern uint64_t PECMD_SetVarRange(int64_t *param_1, LPCWSTR); /* def src\commands\core_b3r_h3.c:350 */
/* 2 site(s) */ extern void PECMD_SetVariableWithPrefix(int64_t *ctx, LPCWSTR key, LPCWSTR value); /* dc 原文权威签名(S11) */
/* 1 site(s) */ extern uint64_t PECMD_SetVectorSize(int64_t *param_1, uint64_t, int); /* def restored_bodies.c:10600 */
/* 1 site(s) */ extern void PECMD_ShowAboutDialog(void); /* def restored_bodies.c:9528 */
/* 1 site(s) */ extern uint64_t PECMD_ShowBrowseFolder(int64_t *param_1, uint16_t *param_2, int64_t, int64_t *param_4); /* def src\commands\core_b3r_d.c:417 */
/* 1 site(s) */ extern void PECMD_ShowContextMenu(char *a, HWND h, int64_t *c, int64_t d, int64_t e); /* dc 原文权威签名(S11) */
/* 1 site(s) */ extern uint64_t PECMD_ShowDriverInstallMsg(uint64_t, uint64_t, uint64_t, uint64_t); /* def src\commands\core_b2b.c:1045 */
/* 1 site(s) */ extern uint64_t PECMD_ShowScreenText(int64_t *param_1, WCHAR *param_2); /* def src\commands\core_b3_remaining.c:1452 */
/* 1 site(s) */ extern void PECMD_SkipIdentifier(uint16_t **pp); /* def src\misc\core_b1_remaining.c:8199 */
/* 1 site(s) */ extern long long * PECMD_SkipLeadingControlChars(long long *param_1); /* def restored_bodies.c:7447 */
/* 1 site(s) */ extern uint64_t * PECMD_SkipLeadingControls(uint64_t *pp); /* def src\misc\core_b1_remaining.c:5796 */
/* 1 site(s) */ extern uint64_t PECMD_SntpResolveServer(int64_t *param_1, LPCWSTR); /* def src\device\core_b3r_g4.c:136 */
/* 1 site(s) */ extern void PECMD_SplitTokenTrimWs(WCHAR **src, WCHAR **dst, int16_t); /* def src\misc\core_remaining_helpers.c:64 */
/* 16 site(s) */ extern void * PECMD_StrBldCopyWide(void *a, const WCHAR *b); /* def restored_bodies.c:7596 */
/* 7 site(s) */ extern WCHAR * PECMD_StrCopyW(WCHAR **ps, LPCWSTR, int64_t); /* def src\runtime\core_var2.c:37 */
/* 1 site(s) */ extern WCHAR * PECMD_StrDupA(WCHAR **ps, LPCWSTR, int64_t, int64_t); /* def restored_bodies.c:7375 */
/* 1 site(s) */ extern void PECMD_StrDupAssign(uint16_t **ps, const uint16_t *src); /* def unimplemented_stubs.c:115 */
/* 1 site(s) */ extern int64_t PECMD_SubCommand(int64_t *param_1, WCHAR *param_2, int64_t *param_3); /* def src\commands\core_b3r_i28b.c:113 */
/* 1 site(s) */ extern uint16_t * PECMD_TableLookupEntry(int64_t, LPCWSTR, int); /* def src\misc\core_b1_remaining.c:7182 */
/* 1 site(s) */ extern LARGE_INTEGER * PECMD_TempPathCommand(int64_t *param_1, LARGE_INTEGER, int64_t); /* def src\device\core_b3r_h2.c:519 */
/* 1 site(s) */ extern void PECMD_TerminateJobObject(int64_t); /* def src\misc\core_b1_remaining.c:7144 */
/* 1 site(s) */ extern DWORD PECMD_ToSysCopyFiles(int64_t, LPCWSTR, uint32_t); /* def restored_bodies.c:10669 */
/* 1 site(s) */ extern WCHAR * PECMD_TokenizeQuotedField(int64_t *param_1, int64_t *param_2, int64_t *param_3, WCHAR, uint16_t); /* def restored_bodies.c:14072 */
/* 1 site(s) */ extern uint64_t PECMD_UpdateDriverSigning(int, int); /* def unimplemented_stubs.c:284 */
/* 1 site(s) */ extern LPCWSTR * PECMD_VarSearchReplace(int64_t *param_1, LPCWSTR); /* def src\commands\core_b3r_h4.c:165 */
/* 1 site(s) */ extern void PECMD_VarWriteValueCap(WCHAR **pval, uint64_t *pcap, const void *src, int64_t); /* def src\runtime\core_var2.c:83 */
/* 1 site(s) */ extern int64_t PECMD_VolumeDeviceCommand(int64_t *param_1, LPCWSTR); /* def src\device\core_b3r_h2.c:1243 */
/* 1 site(s) */ extern int64_t * PECMD_WideToAnsiStr(int64_t *ps, LPCWSTR, int64_t, uint64_t); /* def src\commands\core_b3_remaining.c:12217 */
/* 1 site(s) */ extern uint64_t PECMD_WlanManage(int64_t *param_1, LPCWSTR); /* def src\device\core_b3r_h2.c:1969 */
/* 1 site(s) */ extern LARGE_INTEGER PECMD_WriteFileEncoded(int64_t *script, LARGE_INTEGER arg); /* dc 原文权威签名(S11) */
/* 1 site(s) */ extern uint64_t PECMD_WritePELogonDword(uint64_t, LPCWSTR, uint32_t); /* def src\misc\core_b1_remaining.c:8071 */
/* 1 site(s) */ extern uint64_t PECMD_WriteVarEncoded(int64_t *param_1, LPCWSTR); /* def src\commands\core_b3r_h3.c:182 */
/* 1 site(s) */ extern uint64_t PECMD_WriteVarTruncated(int64_t *param_1, LPCWSTR); /* def src\commands\core_b3r_h3.c:270 */
/* 1 site(s) */ extern uint64_t PECMD_XorEncode(const uint16_t *a, uint32_t, uint64_t); /* def unimplemented_stubs.c:64 */
/* 1 site(s) */ extern uint8_t * PECMD_ZeroStruct_b848(uint8_t *obj); /* def src\commands\core_b3d.c:117 */
/* 1 site(s) */ extern uint64_t * PECMD_ZeroStruct_f934(uint64_t *obj); /* def src\commands\core_b3a.c:97 */
/* 1 site(s) */ extern void thunk_FUN_140064b78(char *a); /* dc 原文权威签名(S11) */
/* 1 site(s) */ extern uint64_t thunk_FUN_1400f429c(void *a, short); /* def unimplemented_stubs.c:394 */

/* ---- Win32 APIs previously called without any visible prototype ---- */
extern BOOL BuildExplicitAccessWithNameW(void*,LPWSTR,DWORD,DWORD,DWORD);
extern DWORD GetNamedSecurityInfoW(LPCWSTR,uint32_t,uint32_t,void**,void**,void**,void**,void**);
extern HDC CreateDCW(LPCWSTR,LPCWSTR,LPCWSTR,const void*);
extern HICON CreateIconFromResource(uint8_t*,DWORD,int,DWORD);
extern HICON CreateIconFromResourceEx(uint8_t*,DWORD,int,DWORD,int,int,uint32_t);
extern HMENU CreateMenu(void);
extern BOOL DestroyCursor(HANDLE);
extern BOOL FileTimeToLocalFileTime(const void*,void*);
extern BOOL LocalFileTimeToFileTime(const void*,void*);
extern BOOL GetDiskFreeSpaceExW(LPCWSTR,void*,void*,void*);
extern BOOL GetDiskFreeSpaceW(LPCWSTR,DWORD*,DWORD*,DWORD*,DWORD*);
extern BOOL GetUserNameW(LPWSTR,DWORD*);
extern BOOL LookupAccountNameW(LPCWSTR,LPCWSTR,void*,DWORD*,LPWSTR,DWORD*,DWORD*);
extern BOOL HeapValidate(HANDLE,DWORD,const void*);
extern BOOL IsRectEmpty(const void*);
extern int LoadStringA(HINSTANCE,uint32_t,char*,int);
extern long RegDeleteKeyW(HKEY,LPCWSTR);
extern long RegLoadKeyW(HKEY,LPCWSTR,LPCWSTR);
extern long RegUnLoadKeyW(HKEY,LPCWSTR);
extern BOOL RegisterHotKey(HWND,int,uint32_t,uint32_t);
extern BOOL ReleaseSemaphore(HANDLE,int32_t,int32_t*);
extern BOOL SetThreadPriority(HANDLE,int);
extern BOOL SetupDiBuildDriverInfoList(void*,void*,DWORD);
extern BOOL SetupDiClassNameFromGuidW(const void*,LPWSTR,DWORD,DWORD*);
extern BOOL SetupDiEnumDriverInfoW(void*,void*,DWORD,DWORD,void*);
extern BOOL SetupDiGetDriverInfoDetailW(void*,void*,const void*,void*,DWORD,DWORD*);
extern BOOL SetupDiSetDeviceInstallParamsW(void*,void*,const void*);
extern BOOL TlsSetValue(DWORD,void*);
extern void free(void*);
extern LPWSTR lstrcatW(wchar_t*,const wchar_t*);
extern int lstrcmpA(const char*,const char*);

#endif /* XPROTO_H */
